export const VISUAL_MODES = [
  'Kaleidoscope Tunnel',
  'Mandelbrot Bloom',
  'Julia Fractal',
  'Plasma Storm',
  'Starfield Warp',
  'Liquid Marble',
  'Electric Ribbons',
  'Sacred Geometry',
  'Audio Pulse Rings',
  'Vortex Grid'
];

export const PALETTE_STYLES = [
  'Prismatic',
  'Cyber Candy',
  'Solar Flare',
  'Deep Ocean',
  'Ultraviolet',
  'Lime Circuit'
];

export const DEFAULT_CONTROLS = {
  visualMode: 'Kaleidoscope Tunnel',
  speed: 0.75,
  colorIntensity: 1.2,
  hueShiftSpeed: 0.38,
  zoom: 1.05,
  rotationSpeed: 0.26,
  complexity: 7,
  symmetry: 10,
  distortion: 0.72,
  glow: 0.42,
  contrast: 1.18,
  brightness: 1.05,
  morphRate: 0.48,
  detailScale: 1,
  warpAmount: 0.62,
  trailStrength: 0.62,
  centerPull: 0.5,
  paletteStyle: 0,
  seed: 4217,
  transparent: false,
  renderSize: 'screen'
};

export const PRESETS = [
  {
    name: 'Neon Tunnel',
    values: {
      ...DEFAULT_CONTROLS,
      visualMode: 'Kaleidoscope Tunnel',
      speed: 0.9,
      colorIntensity: 1.35,
      hueShiftSpeed: 0.55,
      zoom: 1.45,
      rotationSpeed: 0.34,
      complexity: 8,
      symmetry: 12,
      distortion: 0.82,
      glow: 0.5,
      contrast: 1.28,
      brightness: 1.05,
      morphRate: 0.6,
      detailScale: 1.06,
      warpAmount: 0.72,
      trailStrength: 0.76,
      centerPull: 0.7,
      paletteStyle: 1,
      seed: 1308
    }
  },
  {
    name: 'Mandelbrot Bloom',
    values: {
      ...DEFAULT_CONTROLS,
      visualMode: 'Mandelbrot Bloom',
      speed: 0.58,
      colorIntensity: 1.55,
      hueShiftSpeed: 0.32,
      zoom: 1.55,
      rotationSpeed: 0.08,
      complexity: 13,
      symmetry: 4,
      distortion: 0.42,
      glow: 0.48,
      contrast: 1.46,
      brightness: 1.02,
      morphRate: 0.34,
      detailScale: 1.22,
      warpAmount: 0.35,
      trailStrength: 0.58,
      centerPull: 0.58,
      paletteStyle: 4,
      seed: 3809
    }
  },
  {
    name: 'Julia Oracle',
    values: {
      ...DEFAULT_CONTROLS,
      visualMode: 'Julia Fractal',
      speed: 0.68,
      colorIntensity: 1.46,
      hueShiftSpeed: 0.44,
      zoom: 1.18,
      rotationSpeed: -0.18,
      complexity: 15,
      symmetry: 5,
      distortion: 0.58,
      glow: 0.38,
      contrast: 1.5,
      brightness: 1,
      morphRate: 0.72,
      detailScale: 1.4,
      warpAmount: 0.55,
      trailStrength: 0.46,
      centerPull: 0.42,
      paletteStyle: 0,
      seed: 6412
    }
  },
  {
    name: 'Acid Plasma',
    values: {
      ...DEFAULT_CONTROLS,
      visualMode: 'Plasma Storm',
      speed: 1.05,
      colorIntensity: 1.7,
      hueShiftSpeed: 0.78,
      zoom: 0.7,
      rotationSpeed: 0.18,
      complexity: 6,
      symmetry: 7,
      distortion: 1,
      glow: 0.36,
      contrast: 1.42,
      brightness: 1.1,
      morphRate: 0.86,
      detailScale: 0.95,
      warpAmount: 1.04,
      trailStrength: 0.42,
      centerPull: 0.28,
      paletteStyle: 2,
      seed: 9190
    }
  },
  {
    name: 'Hyperspace Bloom',
    values: {
      ...DEFAULT_CONTROLS,
      visualMode: 'Starfield Warp',
      speed: 1.65,
      colorIntensity: 1.4,
      hueShiftSpeed: 0.35,
      zoom: 1.82,
      rotationSpeed: 0.32,
      complexity: 11,
      symmetry: 8,
      distortion: 0.36,
      glow: 0.68,
      contrast: 1.55,
      brightness: 1.18,
      morphRate: 0.5,
      detailScale: 1.1,
      warpAmount: 0.76,
      trailStrength: 0.88,
      centerPull: 1,
      paletteStyle: 0,
      seed: 7340
    }
  },
  {
    name: 'Liquid Chrome',
    values: {
      ...DEFAULT_CONTROLS,
      visualMode: 'Liquid Marble',
      speed: 0.48,
      colorIntensity: 1.2,
      hueShiftSpeed: 0.2,
      zoom: 0.78,
      rotationSpeed: 0.06,
      complexity: 9,
      symmetry: 3,
      distortion: 1.18,
      glow: 0.32,
      contrast: 1.25,
      brightness: 1.08,
      morphRate: 0.42,
      detailScale: 0.82,
      warpAmount: 1.25,
      trailStrength: 0.34,
      centerPull: 0.18,
      paletteStyle: 3,
      seed: 5045
    }
  },
  {
    name: 'Electric Ribbons',
    values: {
      ...DEFAULT_CONTROLS,
      visualMode: 'Electric Ribbons',
      speed: 0.92,
      colorIntensity: 1.75,
      hueShiftSpeed: 0.62,
      zoom: 1.02,
      rotationSpeed: 0.22,
      complexity: 10,
      symmetry: 6,
      distortion: 0.78,
      glow: 0.82,
      contrast: 1.6,
      brightness: 0.95,
      morphRate: 0.74,
      detailScale: 1.18,
      warpAmount: 0.72,
      trailStrength: 0.72,
      centerPull: 0.32,
      paletteStyle: 5,
      seed: 2603
    }
  },
  {
    name: 'Cosmic Mandala',
    values: {
      ...DEFAULT_CONTROLS,
      visualMode: 'Sacred Geometry',
      speed: 0.52,
      colorIntensity: 1.45,
      hueShiftSpeed: 0.24,
      zoom: 0.82,
      rotationSpeed: 0.16,
      complexity: 9,
      symmetry: 18,
      distortion: 0.54,
      glow: 0.62,
      contrast: 1.12,
      brightness: 1.15,
      morphRate: 0.34,
      detailScale: 1.1,
      warpAmount: 0.36,
      trailStrength: 0.5,
      centerPull: 0.72,
      paletteStyle: 4,
      seed: 8421
    }
  },
  {
    name: 'Bass Pulse Rings',
    values: {
      ...DEFAULT_CONTROLS,
      visualMode: 'Audio Pulse Rings',
      speed: 0.86,
      colorIntensity: 1.58,
      hueShiftSpeed: 0.46,
      zoom: 1.12,
      rotationSpeed: 0.12,
      complexity: 8,
      symmetry: 12,
      distortion: 0.7,
      glow: 0.72,
      contrast: 1.38,
      brightness: 1.08,
      morphRate: 0.82,
      detailScale: 1,
      warpAmount: 0.74,
      trailStrength: 0.8,
      centerPull: 0.86,
      paletteStyle: 2,
      seed: 1882
    }
  },
  {
    name: 'Dreamwave Spiral',
    values: {
      ...DEFAULT_CONTROLS,
      visualMode: 'Vortex Grid',
      speed: 0.7,
      colorIntensity: 1.08,
      hueShiftSpeed: 0.28,
      zoom: 1.32,
      rotationSpeed: 0.28,
      complexity: 7,
      symmetry: 6,
      distortion: 0.62,
      glow: 0.7,
      contrast: 1.18,
      brightness: 1.12,
      morphRate: 0.38,
      detailScale: 1.04,
      warpAmount: 0.86,
      trailStrength: 0.82,
      centerPull: 0.78,
      paletteStyle: 1,
      seed: 5114
    }
  }
];

export const CONTROL_META = [
  ['speed', 'Animation speed', 0, 2.5, 0.01],
  ['colorIntensity', 'Color intensity', 0, 2, 0.01],
  ['hueShiftSpeed', 'Hue shift speed', 0, 1.5, 0.01],
  ['zoom', 'Zoom / tunnel depth', 0.15, 2.5, 0.01],
  ['rotationSpeed', 'Rotation speed', -1.5, 1.5, 0.01],
  ['complexity', 'Fractal complexity', 2, 16, 1],
  ['symmetry', 'Symmetry segments', 1, 24, 1],
  ['distortion', 'Wave distortion', 0, 1.5, 0.01],
  ['glow', 'Glow / blur amount', 0, 1, 0.01],
  ['contrast', 'Contrast', 0.5, 2, 0.01],
  ['brightness', 'Brightness', 0.2, 1.8, 0.01],
  ['morphRate', 'Pattern morph rate', 0, 1.5, 0.01],
  ['detailScale', 'Detail scale', 0.25, 2, 0.01],
  ['warpAmount', 'Warp amount', 0, 1.5, 0.01],
  ['trailStrength', 'Trail strength', 0, 1, 0.01],
  ['centerPull', 'Center pull', 0, 1.5, 0.01],
  ['paletteStyle', 'Palette style', 0, PALETTE_STYLES.length - 1, 1]
];
